name: First Workflow

# Trigger: run whenever code is pushed to main branch
on:
  push:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install NASM
        run: sudo apt-get install -y nasm

      - name: Install Make
        run: sudo apt-get install -y make

      - name: Install Autoconf
        run: sudo apt-get install -y autoconf

      - name: Install Automake
        run: sudo apt-get install -y automake

      - name: Install Build-essential
        run: sudo apt-get install -y build-essential

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Install Pkg-config
        run: sudo apt-get install -y pkg-config

      - name: Install Libtool
        run: sudo apt-get install -y libtool

      - name: Install Android NDK
        run: |
          ANDROID_NDK_VERSION=r27d
          wget https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip
          unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux.zip -d $HOME
          mv $HOME/android-ndk-${ANDROID_NDK_VERSION} $HOME/android-ndk
          echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV
          echo "$HOME/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
          NDK_VERSION=$($HOME/android-ndk/ndk-build --version | awk '{print $3}')
          echo "NDK ${NDK_VERSION} installed at: $HOME/android-ndk"