name: First Workflow

# Trigger: run whenever code is pushed to main branch
on:
  push:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Update apt-get
        run: sudo apt-get update

      - name: Install NASM
        run: sudo apt-get install -y nasm

      - name: Install Make
        run: sudo apt-get install -y make

      - name: Install Autoconf
        run: sudo apt-get install -y autoconf

      - name: Install Automake
        run: sudo apt-get install -y automake

      - name: Install Curl
        run: sudo apt-get install -y curl

      - name: Install Unzip
        run: sudo apt-get install -y unzip

      - name: Install Build-essential
        run: sudo apt-get install -y build-essential

      - name: Install Pkg-config
        run: sudo apt-get install -y pkg-config

      - name: Install Libtool
        run: sudo apt-get install -y libtool

      - name: Install Android SDK + NDK + CMake
        run: |
          ANDROID_SDK_HOME=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_HOME
          echo "ANDROID_SDK_HOME=$ANDROID_SDK_HOME" >> $GITHUB_ENV

          # Download commandline tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q commandlinetools-linux-11076708_latest.zip -d $ANDROID_SDK_HOME/cmdline-tools
          mv $ANDROID_SDK_HOME/cmdline-tools/cmdline-tools $ANDROID_SDK_HOME/cmdline-tools/latest

          # Accept licenses
          yes | $ANDROID_SDK_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

          # Define versions
          ANDROID_CMAKE_VERSION=3.22.1
          ANDROID_NDK_VERSION=27.2.12479018

          # Install specific versions
          $ANDROID_SDK_HOME/cmdline-tools/latest/bin/sdkmanager "cmake;${ANDROID_CMAKE_VERSION}" "ndk;${ANDROID_NDK_VERSION}"

          # Export env variables
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_HOME/ndk/${ANDROID_NDK_VERSION}" >> $GITHUB_ENV
          echo "ANDROID_CMAKE_VERSION=${ANDROID_CMAKE_VERSION}" >> $GITHUB_ENV

          # Add SDK CMake to PATH
          echo "$ANDROID_SDK_HOME/cmake/${ANDROID_CMAKE_VERSION}/bin" >> $GITHUB_PATH

      - name: Show SDK path
        run: echo "SDK is at $ANDROID_SDK_HOME"

      - name: Show NDK path
        run: echo "NDK is at $ANDROID_NDK_HOME"

      - name: Show CMake path
        run: echo "CMake $ANDROID_CMAKE_VERSION is at $ANDROID_SDK_HOME/cmake/$ANDROID_CMAKE_VERSION/bin"

      - name: Run setup.sh
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Upload FFmpeg libraries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-libs
          path: output/